/**
 * Capability Registry - All 200+ Capabilities Defined
 * 
 * This file defines ALL capabilities that Ascension AI will support.
 * New capabilities can be added here and they'll be available immediately.
 */

export const CAPABILITIES = [
  // Text & Writing
  {
    id: 'chat_gpt4',
    name: 'Chat GPT-4',
    category: 'text',
    description: 'Advanced AI chat with GPT-4',
    providers: ['openai'],
    default_provider: 'openai',
    cost_per_1k_tokens: 30,
    requires_tier: 'individual',
    executor: 'chat'
  },
  {
    id: 'chat_claude',
    name: 'Chat Claude',
    category: 'text',
    description: 'Advanced AI chat with Claude 3.5',
    providers: ['anthropic'],
    default_provider: 'anthropic',
    cost_per_1k_tokens: 15,
    requires_tier: 'individual',
    executor: 'chat'
  },
  {
    id: 'chat_gemini',
    name: 'Chat Gemini',
    category: 'text',
    description: 'Advanced AI chat with Gemini Pro',
    providers: ['google'],
    default_provider: 'google',
    cost_per_1k_tokens: 25,
    requires_tier: 'individual',
    executor: 'chat'
  },
  {
    id: 'writing_marketing',
    name: 'Marketing Copy',
    category: 'text',
    description: 'Generate marketing copy in brand voice',
    providers: ['openai', 'anthropic', 'google'],
    default_provider: 'openai',
    cost_per_1k_tokens: 30,
    requires_tier: 'individual',
    executor: 'writing'
  },
  {
    id: 'writing_document',
    name: 'Document Writing',
    category: 'text',
    description: 'Write documents, reports, articles',
    providers: ['openai', 'anthropic', 'google'],
    default_provider: 'anthropic',
    cost_per_1k_tokens: 15,
    requires_tier: 'individual',
    executor: 'writing'
  },
  {
    id: 'writing_email',
    name: 'Email Writing',
    category: 'text',
    description: 'Write professional emails',
    providers: ['openai', 'anthropic', 'google'],
    default_provider: 'openai',
    cost_per_1k_tokens: 20,
    requires_tier: 'individual',
    executor: 'writing'
  },
  {
    id: 'writing_script',
    name: 'Script Writing',
    category: 'text',
    description: 'Write video scripts, screenplays',
    providers: ['openai', 'anthropic', 'google'],
    default_provider: 'anthropic',
    cost_per_1k_tokens: 25,
    requires_tier: 'individual',
    executor: 'writing'
  },
  {
    id: 'translation',
    name: 'Translation',
    category: 'text',
    description: 'Translate text between 100+ languages',
    providers: ['google', 'openai'],
    default_provider: 'google',
    cost_per_1k_tokens: 20,
    requires_tier: 'individual',
    executor: 'translation'
  },
  
  // Code & Development
  {
    id: 'code_generation',
    name: 'Code Generation',
    category: 'code',
    description: 'Generate code in any programming language',
    providers: ['openai', 'anthropic', 'google'],
    default_provider: 'openai',
    cost_per_1k_tokens: 30,
    requires_tier: 'individual',
    executor: 'code'
  },
  {
    id: 'code_review',
    name: 'Code Review',
    category: 'code',
    description: 'Review code for bugs, security, best practices',
    providers: ['openai', 'anthropic'],
    default_provider: 'anthropic',
    cost_per_1k_tokens: 25,
    requires_tier: 'individual',
    executor: 'code'
  },
  {
    id: 'code_debugging',
    name: 'Code Debugging',
    category: 'code',
    description: 'Debug and fix code errors',
    providers: ['openai', 'anthropic'],
    default_provider: 'openai',
    cost_per_1k_tokens: 30,
    requires_tier: 'individual',
    executor: 'code'
  },
  {
    id: 'code_execution',
    name: 'Code Execution',
    category: 'code',
    description: 'Execute code in sandboxed environment',
    providers: ['local'],
    default_provider: 'local',
    cost_per_1k_tokens: 5,
    requires_tier: 'individual',
    executor: 'code'
  },
  {
    id: 'code_completion',
    name: 'Code Completion',
    category: 'code',
    description: 'Real-time code completion',
    providers: ['openai', 'anthropic'],
    default_provider: 'openai',
    cost_per_1k_tokens: 20,
    requires_tier: 'individual',
    executor: 'code'
  },
  {
    id: 'test_generation',
    name: 'Test Generation',
    category: 'code',
    description: 'Generate unit tests for code',
    providers: ['openai', 'anthropic'],
    default_provider: 'openai',
    cost_per_1k_tokens: 25,
    requires_tier: 'individual',
    executor: 'code'
  },
  {
    id: 'documentation_generation',
    name: 'Documentation Generation',
    category: 'code',
    description: 'Generate code documentation',
    providers: ['openai', 'anthropic'],
    default_provider: 'openai',
    cost_per_1k_tokens: 20,
    requires_tier: 'individual',
    executor: 'code'
  },
  
  // Image & Design
  {
    id: 'image_generation_dalle',
    name: 'Image Generation (DALL-E 3)',
    category: 'vision',
    description: 'Generate images with DALL-E 3',
    providers: ['openai'],
    default_provider: 'openai',
    cost_per_1k_tokens: 40,
    requires_tier: 'individual',
    executor: 'image'
  },
  {
    id: 'image_generation_midjourney',
    name: 'Image Generation (Midjourney)',
    category: 'vision',
    description: 'Generate photorealistic images with Midjourney',
    providers: ['midjourney'],
    default_provider: 'midjourney',
    cost_per_1k_tokens: 50,
    requires_tier: 'individual',
    executor: 'image'
  },
  {
    id: 'image_generation_stable',
    name: 'Image Generation (Stable Diffusion)',
    category: 'vision',
    description: 'Generate images with Stable Diffusion',
    providers: ['stability'],
    default_provider: 'stability',
    cost_per_1k_tokens: 30,
    requires_tier: 'individual',
    executor: 'image'
  },
  {
    id: 'image_editing',
    name: 'Image Editing',
    category: 'vision',
    description: 'Edit and manipulate images',
    providers: ['openai', 'stability'],
    default_provider: 'openai',
    cost_per_1k_tokens: 35,
    requires_tier: 'individual',
    executor: 'image'
  },
  {
    id: 'image_generation_adobe',
    name: 'Image Generation (Adobe Firefly)',
    category: 'vision',
    description: 'Generate images with Adobe Firefly',
    providers: ['adobe'],
    default_provider: 'adobe',
    cost_per_1k_tokens: 45,
    requires_tier: 'professional',
    executor: 'image'
  },
  {
    id: 'design_generation',
    name: 'Design Generation',
    category: 'vision',
    description: 'Generate designs, layouts, graphics',
    providers: ['canva', 'figma'],
    default_provider: 'canva',
    cost_per_1k_tokens: 50,
    requires_tier: 'professional',
    executor: 'design'
  },
  
  // Audio & Music
  {
    id: 'text_to_speech',
    name: 'Text-to-Speech',
    category: 'audio',
    description: 'Convert text to speech with ElevenLabs',
    providers: ['elevenlabs'],
    default_provider: 'elevenlabs',
    cost_per_1k_tokens: 30,
    requires_tier: 'individual',
    executor: 'audio'
  },
  {
    id: 'speech_to_text',
    name: 'Speech-to-Text',
    category: 'audio',
    description: 'Convert speech to text with Whisper',
    providers: ['openai'],
    default_provider: 'placeholder',
    cost_per_1k_tokens: 25,
    requires_tier: 'individual',
    executor: 'audio'
  },
  {
    id: 'music_generation_suno',
    name: 'Music Generation (Suno)',
    category: 'audio',
    description: 'Generate music with Suno AI',
    providers: ['suno'],
    default_provider: 'suno',
    cost_per_1k_tokens: 40,
    requires_tier: 'individual',
    executor: 'audio'
  },
  {
    id: 'music_generation_udio',
    name: 'Music Generation (Udio)',
    category: 'audio',
    description: 'Generate music with Udio',
    providers: ['udio'],
    default_provider: 'udio',
    cost_per_1k_tokens: 40,
    requires_tier: 'individual',
    executor: 'audio'
  },
  {
    id: 'audio_editing',
    name: 'Audio Editing',
    category: 'audio',
    description: 'Edit and manipulate audio',
    providers: ['elevenlabs', 'openai'],
    default_provider: 'openai',
    cost_per_1k_tokens: 35,
    requires_tier: 'individual',
    executor: 'audio'
  },
  {
    id: 'voice_cloning',
    name: 'Voice Cloning',
    category: 'audio',
    description: 'Clone voices with ElevenLabs',
    providers: ['elevenlabs'],
    default_provider: 'elevenlabs',
    cost_per_1k_tokens: 100,
    requires_tier: 'professional',
    executor: 'audio'
  },
  
  // Video
  {
    id: 'video_generation_runway',
    name: 'Video Generation (Runway)',
    category: 'video',
    description: 'Generate videos with Runway ML',
    providers: ['runway'],
    default_provider: 'runway',
    cost_per_1k_tokens: 100,
    requires_tier: 'professional',
    executor: 'video'
  },
  {
    id: 'video_generation_pika',
    name: 'Video Generation (Pika Labs)',
    category: 'video',
    description: 'Generate videos with Pika Labs',
    providers: ['pika'],
    default_provider: 'pika',
    cost_per_1k_tokens: 100,
    requires_tier: 'professional',
    executor: 'video'
  },
  {
    id: 'video_generation_luma',
    name: 'Video Generation (Luma Dream Machine)',
    category: 'video',
    description: 'Generate videos with Luma Dream Machine',
    providers: ['luma'],
    default_provider: 'luma',
    cost_per_1k_tokens: 100,
    requires_tier: 'professional',
    executor: 'video'
  },
  {
    id: 'video_generation_stable',
    name: 'Video Generation (Stable Video)',
    category: 'video',
    description: 'Generate videos with Stable Video Diffusion',
    providers: ['stability'],
    default_provider: 'stability',
    cost_per_1k_tokens: 80,
    requires_tier: 'professional',
    executor: 'video'
  },
  {
    id: 'video_editing',
    name: 'Video Editing',
    category: 'video',
    description: 'Edit and manipulate videos',
    providers: ['runway', 'adobe'],
    default_provider: 'runway',
    cost_per_1k_tokens: 120,
    requires_tier: 'professional',
    executor: 'video'
  },
  
  // Web & Search
  {
    id: 'web_search',
    name: 'Web Search',
    category: 'web',
    description: 'Search the web with citations',
    providers: ['perplexity', 'google'],
    default_provider: 'perplexity',
    cost_per_1k_tokens: 15,
    requires_tier: 'individual',
    executor: 'web'
  },
  {
    id: 'web_browsing',
    name: 'Web Browsing',
    category: 'web',
    description: 'Browse the web autonomously',
    providers: ['openai', 'anthropic'],
    default_provider: 'openai',
    cost_per_1k_tokens: 30,
    requires_tier: 'individual',
    executor: 'web'
  },
  {
    id: 'file_analysis',
    name: 'File Analysis',
    category: 'data',
    description: 'Analyze files (PDF, DOCX, images, etc.)',
    providers: ['openai', 'anthropic', 'google'],
    default_provider: 'openai',
    cost_per_1k_tokens: 25,
    requires_tier: 'individual',
    executor: 'data'
  },
  
  // AP Capabilities (Already Built, Will Integrate)
  {
    id: 'intelligence_sweep',
    name: 'Intelligence Sweep',
    category: 'intelligence',
    description: 'Intelligence sweep across 10 domains',
    providers: ['custom'],
    default_provider: 'custom',
    cost_per_1k_tokens: 10,
    requires_tier: 'individual',
    executor: 'intelligence'
  },
  {
    id: 'context_memory',
    name: 'Context Memory',
    category: 'intelligence',
    description: 'Context-aware memory (characters, arcs, themes)',
    providers: ['custom'],
    default_provider: 'custom',
    cost_per_1k_tokens: 5,
    requires_tier: 'individual',
    executor: 'intelligence'
  },
  {
    id: 'proactive_intelligence',
    name: 'Proactive Intelligence',
    category: 'intelligence',
    description: 'Proactive AP behavior with push notifications',
    providers: ['custom'],
    default_provider: 'custom',
    cost_per_1k_tokens: 5,
    requires_tier: 'individual',
    executor: 'intelligence'
  },
  {
    id: 'business_growth',
    name: 'Business Growth',
    category: 'business',
    description: 'Business growth strategies and intelligence',
    providers: ['custom'],
    default_provider: 'custom',
    cost_per_1k_tokens: 10,
    requires_tier: 'individual',
    executor: 'business'
  },
  {
    id: 'relationship_graph',
    name: 'Relationship Graph',
    category: 'social',
    description: 'Relationship graph engine',
    providers: ['custom'],
    default_provider: 'custom',
    cost_per_1k_tokens: 5,
    requires_tier: 'individual',
    executor: 'social'
  },
  {
    id: 'emotional_intelligence',
    name: 'Emotional Intelligence',
    category: 'health',
    description: 'Emotional intelligence and tracking',
    providers: ['custom'],
    default_provider: 'custom',
    cost_per_1k_tokens: 5,
    requires_tier: 'individual',
    executor: 'health'
  },
  
  // Native Ascension overlay capabilities (replace outside AI)
  {
    id: 'ascension_chat',
    name: 'Ascension Native Chat',
    category: 'text',
    description: 'General chat powered by native Ascension AI core',
    providers: ['ascension-native'],
    default_provider: 'ascension-native',
    cost_per_1k_tokens: 0,
    requires_tier: 'individual',
    executor: 'chat'
  },
  {
    id: 'ascension_home',
    name: 'Ascension HomeOS',
    category: 'home',
    description: 'Household and co-parenting coordination',
    providers: ['ascension-native'],
    default_provider: 'ascension-native',
    cost_per_1k_tokens: 0,
    requires_tier: 'individual',
    executor: 'home'
  },
  {
    id: 'ascension_sprout',
    name: 'Ascension Sprout',
    category: 'sprout',
    description: 'Child development and learning paths',
    providers: ['ascension-native'],
    default_provider: 'ascension-native',
    cost_per_1k_tokens: 0,
    requires_tier: 'individual',
    executor: 'sprout'
  },
  {
    id: 'ascension_family',
    name: 'Ascension FamilyOS',
    category: 'family',
    description: 'Family enterprise, tree, and governance',
    providers: ['ascension-native'],
    default_provider: 'ascension-native',
    cost_per_1k_tokens: 0,
    requires_tier: 'individual',
    executor: 'family'
  },
  {
    id: 'ascension_health',
    name: 'Ascension Health',
    category: 'health',
    description: 'Health, wellness, and symptom guidance',
    providers: ['ascension-native'],
    default_provider: 'ascension-native',
    cost_per_1k_tokens: 0,
    requires_tier: 'individual',
    executor: 'health'
  },
  {
    id: 'ascension_finance',
    name: 'Ascension Financial Intelligence',
    category: 'finance',
    description: 'Financial analysis, planning, and opportunity finding',
    providers: ['ascension-native'],
    default_provider: 'ascension-native',
    cost_per_1k_tokens: 0,
    requires_tier: 'individual',
    executor: 'finance'
  },
  {
    id: 'ascension_trading',
    name: 'Ascension Trading Intelligence',
    category: 'finance',
    description: 'Multi-market analysis, backtesting, and paper trading',
    providers: ['ascension-native'],
    default_provider: 'ascension-native',
    cost_per_1k_tokens: 0,
    requires_tier: 'individual',
    executor: 'finance'
  },
  {
    id: 'ascension_vision',
    name: 'Ascension Vision',
    category: 'vision',
    description: 'Camera and environmental understanding',
    providers: ['ascension-native'],
    default_provider: 'ascension-native',
    cost_per_1k_tokens: 0,
    requires_tier: 'individual',
    executor: 'vision'
  },
  {
    id: 'ascension_legal',
    name: 'Ascension Legal Assistant',
    category: 'documents',
    description: 'Document review, contract analysis, and legal guidance flags',
    providers: ['ascension-native'],
    default_provider: 'ascension-native',
    cost_per_1k_tokens: 0,
    requires_tier: 'individual',
    executor: 'documents'
  },
  {
    id: 'ascension_travel',
    name: 'Ascension Travel',
    category: 'home',
    description: 'Trip planning, flight search, and itinerary preparation',
    providers: ['ascension-native'],
    default_provider: 'ascension-native',
    cost_per_1k_tokens: 0,
    requires_tier: 'individual',
    executor: 'home'
  },
  {
    id: 'ascension_realestate',
    name: 'Ascension Real Estate',
    category: 'home',
    description: 'Housing search, lease review, and property analysis',
    providers: ['ascension-native'],
    default_provider: 'ascension-native',
    cost_per_1k_tokens: 0,
    requires_tier: 'individual',
    executor: 'home'
  },
  {
    id: 'ascension_research',
    name: 'Ascension Research',
    category: 'research',
    description: 'Deep research with source comparison and citation preparation',
    providers: ['ascension-native'],
    default_provider: 'ascension-native',
    cost_per_1k_tokens: 0,
    requires_tier: 'individual',
    executor: 'research'
  },
  {
    id: 'ascension_events',
    name: 'Ascension Events',
    category: 'home',
    description: 'Event planning, coordination, and logistics',
    providers: ['ascension-native'],
    default_provider: 'ascension-native',
    cost_per_1k_tokens: 0,
    requires_tier: 'individual',
    executor: 'home'
  },
  {
    id: 'ascension_automotive',
    name: 'Ascension Automotive',
    category: 'home',
    description: 'Vehicle maintenance, diagnostics, and buying guidance',
    providers: ['ascension-native'],
    default_provider: 'ascension-native',
    cost_per_1k_tokens: 0,
    requires_tier: 'individual',
    executor: 'home'
  },
  {
    id: 'ascension_pets',
    name: 'Ascension Pets',
    category: 'home',
    description: 'Pet care, health, training, and nutrition guidance',
    providers: ['ascension-native'],
    default_provider: 'ascension-native',
    cost_per_1k_tokens: 0,
    requires_tier: 'individual',
    executor: 'home'
  },
  {
    id: 'ascension_weather',
    name: 'Ascension Weather',
    category: 'environment',
    description: 'Weather-aware planning and safety recommendations',
    providers: ['ascension-native'],
    default_provider: 'ascension-native',
    cost_per_1k_tokens: 0,
    requires_tier: 'individual',
    executor: 'environment'
  },
  {
    id: 'ascension_nutrition',
    name: 'Ascension Nutrition',
    category: 'health',
    description: 'Meal planning, nutrition analysis, and dietary guidance',
    providers: ['ascension-native'],
    default_provider: 'ascension-native',
    cost_per_1k_tokens: 0,
    requires_tier: 'individual',
    executor: 'health'
  },
  {
    id: 'ascension_fitness',
    name: 'Ascension Fitness',
    category: 'health',
    description: 'Workout plans, form guidance, and progress tracking',
    providers: ['ascension-native'],
    default_provider: 'ascension-native',
    cost_per_1k_tokens: 0,
    requires_tier: 'individual',
    executor: 'health'
  },
  {
    id: 'ascension_career',
    name: 'Ascension Career',
    category: 'career',
    description: 'Resume review, job matching, and career planning',
    providers: ['ascension-native'],
    default_provider: 'ascension-native',
    cost_per_1k_tokens: 0,
    requires_tier: 'individual',
    executor: 'career'
  },
  {
    id: 'ascension_relationships',
    name: 'Ascension Relationships',
    category: 'relationships',
    description: 'Communication support, follow-up prep, and relationship context',
    providers: ['ascension-native'],
    default_provider: 'ascension-native',
    cost_per_1k_tokens: 0,
    requires_tier: 'individual',
    executor: 'relationships'
  },
  {
    id: 'ascension_creative',
    name: 'Ascension Creative',
    category: 'creation',
    description: 'Writing, music, art, and content generation planning',
    providers: ['ascension-native'],
    default_provider: 'ascension-native',
    cost_per_1k_tokens: 0,
    requires_tier: 'individual',
    executor: 'creation'
  },
  {
    id: 'ascension_code',
    name: 'Ascension Code',
    category: 'code',
    description: 'Code generation, review, debugging, and architecture planning',
    providers: ['ascension-native'],
    default_provider: 'ascension-native',
    cost_per_1k_tokens: 0,
    requires_tier: 'individual',
    executor: 'code'
  },
  {
    id: 'ascension_learning',
    name: 'Ascension Learning',
    category: 'learning',
    description: 'Adaptive skill paths, practice generation, and concept explanation',
    providers: ['ascension-native'],
    default_provider: 'ascension-native',
    cost_per_1k_tokens: 0,
    requires_tier: 'individual',
    executor: 'learning'
  },
  {
    id: 'ascension_meetings',
    name: 'Ascension Meetings',
    category: 'productivity',
    description: 'Meeting transcription, summaries, and action-item extraction',
    providers: ['ascension-native'],
    default_provider: 'ascension-native',
    cost_per_1k_tokens: 0,
    requires_tier: 'individual',
    executor: 'productivity'
  },
  {
    id: 'ascension_voice',
    name: 'Ascension Voice',
    category: 'voice',
    description: 'Voice commands, transcription, and speech-driven control',
    providers: ['ascension-native'],
    default_provider: 'ascension-native',
    cost_per_1k_tokens: 0,
    requires_tier: 'individual',
    executor: 'voice'
  },
  {
    id: 'ascension_security',
    name: 'Ascension Security',
    category: 'security',
    description: 'Security analysis, threat flags, and privacy guidance',
    providers: ['ascension-native'],
    default_provider: 'ascension-native',
    cost_per_1k_tokens: 0,
    requires_tier: 'individual',
    executor: 'security'
  },
  {
    id: 'ascension_psychology',
    name: 'Ascension Psychology',
    category: 'psychology',
    description: 'Human behavior, emotion, motivation, cognition, and mental health guidance',
    providers: ['ascension-native'],
    default_provider: 'ascension-native',
    cost_per_1k_tokens: 0,
    requires_tier: 'individual',
    executor: 'psychology'
  },
  {
    id: 'ascension_human_life',
    name: 'Ascension Human Life',
    category: 'human_life',
    description: 'Comprehensive guidance across identity, health, money, relationships, home, time, learning, creativity, meaning, and transitions',
    providers: ['ascension-native'],
    default_provider: 'ascension-native',
    cost_per_1k_tokens: 0,
    requires_tier: 'individual',
    executor: 'human_life'
  },
  {
    id: 'ascension_spirituality',
    name: 'Ascension Spirituality',
    category: 'spirituality',
    description: 'Faith, meaning, meditation, ritual, nature, legacy, and existential exploration',
    providers: ['ascension-native'],
    default_provider: 'ascension-native',
    cost_per_1k_tokens: 0,
    requires_tier: 'individual',
    executor: 'spirituality'
  },
  {
    id: 'ascension_grief',
    name: 'Ascension Grief',
    category: 'human_life',
    description: 'Loss, bereavement, transition, and emotional support',
    providers: ['ascension-native'],
    default_provider: 'ascension-native',
    cost_per_1k_tokens: 0,
    requires_tier: 'individual',
    executor: 'human_life'
  },
  {
    id: 'ascension_mental_health',
    name: 'Ascension Mental Health',
    category: 'psychology',
    description: 'Stress, anxiety, mood, therapy navigation, and emotional regulation',
    providers: ['ascension-native'],
    default_provider: 'ascension-native',
    cost_per_1k_tokens: 0,
    requires_tier: 'individual',
    executor: 'psychology'
  },
  {
    id: 'ascension_communication',
    name: 'Ascension Communication',
    category: 'psychology',
    description: 'Difficult conversations, feedback, listening, and conflict resolution',
    providers: ['ascension-native'],
    default_provider: 'ascension-native',
    cost_per_1k_tokens: 0,
    requires_tier: 'individual',
    executor: 'psychology'
  },
  {
    id: 'ascension_habits',
    name: 'Ascension Habits',
    category: 'psychology',
    description: 'Habit formation, behavior change, cue-routine-reward loops, and identity-based change',
    providers: ['ascension-native'],
    default_provider: 'ascension-native',
    cost_per_1k_tokens: 0,
    requires_tier: 'individual',
    executor: 'psychology'
  },
  {
    id: 'ascension_stress',
    name: 'Ascension Stress',
    category: 'psychology',
    description: 'Stress recognition, regulation, recovery, and burnout prevention',
    providers: ['ascension-native'],
    default_provider: 'ascension-native',
    cost_per_1k_tokens: 0,
    requires_tier: 'individual',
    executor: 'psychology'
  },
  {
    id: 'ascension_sleep',
    name: 'Ascension Sleep',
    category: 'health',
    description: 'Sleep hygiene, circadian rhythm, and recovery planning',
    providers: ['ascension-native'],
    default_provider: 'ascension-native',
    cost_per_1k_tokens: 0,
    requires_tier: 'individual',
    executor: 'health'
  },
  {
    id: 'ascension_parenting',
    name: 'Ascension Parenting',
    category: 'home',
    description: 'Child development, discipline, co-parenting, and parent support',
    providers: ['ascension-native'],
    default_provider: 'ascension-native',
    cost_per_1k_tokens: 0,
    requires_tier: 'individual',
    executor: 'home'
  },
  {
    id: 'ascension_mindfulness',
    name: 'Ascension Mindfulness',
    category: 'spirituality',
    description: 'Presence, meditation, breathing, and attention training',
    providers: ['ascension-native'],
    default_provider: 'ascension-native',
    cost_per_1k_tokens: 0,
    requires_tier: 'individual',
    executor: 'spirituality'
  },
  {
    id: 'ascension_time',
    name: 'Ascension Time',
    category: 'productivity',
    description: 'Time management, energy mapping, priorities, and anti-procrastination',
    providers: ['ascension-native'],
    default_provider: 'ascension-native',
    cost_per_1k_tokens: 0,
    requires_tier: 'individual',
    executor: 'productivity'
  },
  {
    id: 'ascension_confidence',
    name: 'Ascension Confidence',
    category: 'psychology',
    description: 'Self-efficacy, confidence building, and self-doubt navigation',
    providers: ['ascension-native'],
    default_provider: 'ascension-native',
    cost_per_1k_tokens: 0,
    requires_tier: 'individual',
    executor: 'psychology'
  },
  {
    id: 'ascension_aging',
    name: 'Ascension Aging',
    category: 'health',
    description: 'Healthy aging, longevity, and life-stage adaptation',
    providers: ['ascension-native'],
    default_provider: 'ascension-native',
    cost_per_1k_tokens: 0,
    requires_tier: 'individual',
    executor: 'health'
  },
  {
    id: 'ascension_addiction',
    name: 'Ascension Addiction',
    category: 'psychology',
    description: 'Substance and behavioral addiction support, recovery, and professional referrals',
    providers: ['ascension-native'],
    default_provider: 'ascension-native',
    cost_per_1k_tokens: 0,
    requires_tier: 'individual',
    executor: 'psychology'
  },
  {
    id: 'ascension_conflict',
    name: 'Ascension Conflict',
    category: 'psychology',
    description: 'Dispute resolution, de-escalation, and repair strategies',
    providers: ['ascension-native'],
    default_provider: 'ascension-native',
    cost_per_1k_tokens: 0,
    requires_tier: 'individual',
    executor: 'psychology'
  },
  {
    id: 'ascension_dating',
    name: 'Ascension Dating',
    category: 'relationships',
    description: 'Dating strategy, safety, boundaries, and communication',
    providers: ['ascension-native'],
    default_provider: 'ascension-native',
    cost_per_1k_tokens: 0,
    requires_tier: 'individual',
    executor: 'relationships'
  },
  {
    id: 'ascension_cooking',
    name: 'Ascension Cooking',
    category: 'home',
    description: 'Meal planning, recipes, and kitchen guidance',
    providers: ['ascension-native'],
    default_provider: 'ascension-native',
    cost_per_1k_tokens: 0,
    requires_tier: 'individual',
    executor: 'home'
  },
  {
    id: 'ascension_social',
    name: 'Ascension Social',
    category: 'relationships',
    description: 'Friendship, networking, social skills, and community',
    providers: ['ascension-native'],
    default_provider: 'ascension-native',
    cost_per_1k_tokens: 0,
    requires_tier: 'individual',
    executor: 'relationships'
  },
  {
    id: 'ascension_volunteering',
    name: 'Ascension Volunteering',
    category: 'community',
    description: 'Service, volunteering, and community contribution matching',
    providers: ['ascension-native'],
    default_provider: 'ascension-native',
    cost_per_1k_tokens: 0,
    requires_tier: 'individual',
    executor: 'community'
  },
  {
    id: 'ascension_focus',
    name: 'Ascension Focus',
    category: 'productivity',
    description: 'Deep work, attention management, and distraction reduction',
    providers: ['ascension-native'],
    default_provider: 'ascension-native',
    cost_per_1k_tokens: 0,
    requires_tier: 'individual',
    executor: 'productivity'
  },
  {
    id: 'ascension_meditation',
    name: 'Ascension Meditation',
    category: 'spirituality',
    description: 'Guided meditation, body scans, and contemplative practices',
    providers: ['ascension-native'],
    default_provider: 'ascension-native',
    cost_per_1k_tokens: 0,
    requires_tier: 'individual',
    executor: 'spirituality'
  },
  {
    id: 'ascension_garden',
    name: 'Ascension Garden',
    category: 'home',
    description: 'Garden planning, plant care, and growing guidance',
    providers: ['ascension-native'],
    default_provider: 'ascension-native',
    cost_per_1k_tokens: 0,
    requires_tier: 'individual',
    executor: 'home'
  },
  {
    id: 'ascension_fashion',
    name: 'Ascension Fashion',
    category: 'lifestyle',
    description: 'Style, wardrobe, and occasion-appropriate dressing',
    providers: ['ascension-native'],
    default_provider: 'ascension-native',
    cost_per_1k_tokens: 0,
    requires_tier: 'individual',
    executor: 'lifestyle'
  },
  {
    id: 'ascension_repair',
    name: 'Ascension Repair',
    category: 'home',
    description: 'DIY repairs, maintenance, and when-to-call-a-pro guidance',
    providers: ['ascension-native'],
    default_provider: 'ascension-native',
    cost_per_1k_tokens: 0,
    requires_tier: 'individual',
    executor: 'home'
  },
  {
    id: 'ascension_music',
    name: 'Ascension Music',
    category: 'creation',
    description: 'Music theory, composition, practice, and listening guidance',
    providers: ['ascension-native'],
    default_provider: 'ascension-native',
    cost_per_1k_tokens: 0,
    requires_tier: 'individual',
    executor: 'creation'
  },
  {
    id: 'ascension_art',
    name: 'Ascension Art',
    category: 'creation',
    description: 'Art techniques, critiques, and creative direction',
    providers: ['ascension-native'],
    default_provider: 'ascension-native',
    cost_per_1k_tokens: 0,
    requires_tier: 'individual',
    executor: 'creation'
  },
  {
    id: 'ascension_writing',
    name: 'Ascension Writing',
    category: 'creation',
    description: 'Writing craft, editing, voice, and storytelling',
    providers: ['ascension-native'],
    default_provider: 'ascension-native',
    cost_per_1k_tokens: 0,
    requires_tier: 'individual',
    executor: 'creation'
  },
  {
    id: 'ascension_movies',
    name: 'Ascension Movies',
    category: 'entertainment',
    description: 'Film and TV recommendations, analysis, and watch planning',
    providers: ['ascension-native'],
    default_provider: 'ascension-native',
    cost_per_1k_tokens: 0,
    requires_tier: 'individual',
    executor: 'entertainment'
  },
  {
    id: 'ascension_books',
    name: 'Ascension Books',
    category: 'entertainment',
    description: 'Book recommendations, analysis, and reading planning',
    providers: ['ascension-native'],
    default_provider: 'ascension-native',
    cost_per_1k_tokens: 0,
    requires_tier: 'individual',
    executor: 'entertainment'
  },
  {
    id: 'ascension_news',
    name: 'Ascension News',
    category: 'research',
    description: 'News curation, bias awareness, and summary synthesis',
    providers: ['ascension-native'],
    default_provider: 'ascension-native',
    cost_per_1k_tokens: 0,
    requires_tier: 'individual',
    executor: 'research'
  },
  {
    id: 'ascension_sports',
    name: 'Ascension Sports',
    category: 'entertainment',
    description: 'Sports analysis, training, and fan engagement',
    providers: ['ascension-native'],
    default_provider: 'ascension-native',
    cost_per_1k_tokens: 0,
    requires_tier: 'individual',
    executor: 'entertainment'
  },
  {
    id: 'ascension_games',
    name: 'Ascension Games',
    category: 'entertainment',
    description: 'Game recommendations, strategy, and design discussion',
    providers: ['ascension-native'],
    default_provider: 'ascension-native',
    cost_per_1k_tokens: 0,
    requires_tier: 'individual',
    executor: 'entertainment'
  },
  {
    id: 'ascension_shopping',
    name: 'Ascension Shopping',
    category: 'lifestyle',
    description: 'Product research, comparison, and value-based buying',
    providers: ['ascension-native'],
    default_provider: 'ascension-native',
    cost_per_1k_tokens: 0,
    requires_tier: 'individual',
    executor: 'lifestyle'
  },
  {
    id: 'ascension_investing',
    name: 'Ascension Investing',
    category: 'finance',
    description: 'Portfolio thinking, asset allocation, and long-term investing',
    providers: ['ascension-native'],
    default_provider: 'ascension-native',
    cost_per_1k_tokens: 0,
    requires_tier: 'individual',
    executor: 'finance'
  },
  {
    id: 'ascension_taxes',
    name: 'Ascension Taxes',
    category: 'finance',
    description: 'Tax organization, deduction discovery, and preparer coordination',
    providers: ['ascension-native'],
    default_provider: 'ascension-native',
    cost_per_1k_tokens: 0,
    requires_tier: 'individual',
    executor: 'finance'
  },
  {
    id: 'ascension_insurance',
    name: 'Ascension Insurance',
    category: 'finance',
    description: 'Insurance review, comparison, and gap analysis',
    providers: ['ascension-native'],
    default_provider: 'ascension-native',
    cost_per_1k_tokens: 0,
    requires_tier: 'individual',
    executor: 'finance'
  },
  {
    id: 'ascension_moving',
    name: 'Ascension Moving',
    category: 'home',
    description: 'Relocation planning, checklists, and logistics',
    providers: ['ascension-native'],
    default_provider: 'ascension-native',
    cost_per_1k_tokens: 0,
    requires_tier: 'individual',
    executor: 'home'
  },
  {
    id: 'ascension_cleaning',
    name: 'Ascension Cleaning',
    category: 'home',
    description: 'Cleaning routines, schedules, and product guidance',
    providers: ['ascension-native'],
    default_provider: 'ascension-native',
    cost_per_1k_tokens: 0,
    requires_tier: 'individual',
    executor: 'home'
  },
  {
    id: 'ascension_philosophy',
    name: 'Ascension Philosophy',
    category: 'knowledge',
    description: 'Philosophical questions, schools of thought, and ethical reasoning',
    providers: ['ascension-native'],
    default_provider: 'ascension-native',
    cost_per_1k_tokens: 0,
    requires_tier: 'individual',
    executor: 'knowledge'
  },
  {
    id: 'ascension_history',
    name: 'Ascension History',
    category: 'knowledge',
    description: 'Historical context, events, and lessons',
    providers: ['ascension-native'],
    default_provider: 'ascension-native',
    cost_per_1k_tokens: 0,
    requires_tier: 'individual',
    executor: 'knowledge'
  },
  {
    id: 'ascension_science',
    name: 'Ascension Science',
    category: 'knowledge',
    description: 'Scientific concepts, literacy, and exploration',
    providers: ['ascension-native'],
    default_provider: 'ascension-native',
    cost_per_1k_tokens: 0,
    requires_tier: 'individual',
    executor: 'knowledge'
  },
  {
    id: 'ascension_math',
    name: 'Ascension Math',
    category: 'knowledge',
    description: 'Math explanation, problem-solving, and tutoring',
    providers: ['ascension-native'],
    default_provider: 'ascension-native',
    cost_per_1k_tokens: 0,
    requires_tier: 'individual',
    executor: 'knowledge'
  },
  {
    id: 'ascension_language',
    name: 'Ascension Language',
    category: 'knowledge',
    description: 'Language learning, translation, and conversation practice',
    providers: ['ascension-native'],
    default_provider: 'ascension-native',
    cost_per_1k_tokens: 0,
    requires_tier: 'individual',
    executor: 'knowledge'
  },
  {
    id: 'ascension_culture',
    name: 'Ascension Culture',
    category: 'knowledge',
    description: 'Cultural understanding, etiquette, and context',
    providers: ['ascension-native'],
    default_provider: 'ascension-native',
    cost_per_1k_tokens: 0,
    requires_tier: 'individual',
    executor: 'knowledge'
  },
  {
    id: 'ascension_ethics',
    name: 'Ascension Ethics',
    category: 'knowledge',
    description: 'Moral reasoning, dilemma navigation, and values clarification',
    providers: ['ascension-native'],
    default_provider: 'ascension-native',
    cost_per_1k_tokens: 0,
    requires_tier: 'individual',
    executor: 'knowledge'
  },
  {
    id: 'ascension_environment',
    name: 'Ascension Environment',
    category: 'environment',
    description: 'Sustainability, climate, and ecological action planning',
    providers: ['ascension-native'],
    default_provider: 'ascension-native',
    cost_per_1k_tokens: 0,
    requires_tier: 'individual',
    executor: 'environment'
  },
  {
    id: 'ascension_activism',
    name: 'Ascension Activism',
    category: 'community',
    description: 'Civic action, advocacy, and community organizing',
    providers: ['ascension-native'],
    default_provider: 'ascension-native',
    cost_per_1k_tokens: 0,
    requires_tier: 'individual',
    executor: 'community'
  },
  {
    id: 'ascension_project',
    name: 'Ascension Project',
    category: 'work',
    description: 'Project planning, milestones, and delivery tracking',
    providers: ['ascension-native'],
    default_provider: 'ascension-native',
    cost_per_1k_tokens: 0,
    requires_tier: 'individual',
    executor: 'work'
  },
  {
    id: 'ascension_task',
    name: 'Ascension Task',
    category: 'work',
    description: 'Task breakdown, prioritization, and execution support',
    providers: ['ascension-native'],
    default_provider: 'ascension-native',
    cost_per_1k_tokens: 0,
    requires_tier: 'individual',
    executor: 'work'
  },
  {
    id: 'ascension_remote',
    name: 'Ascension Remote',
    category: 'work',
    description: 'Remote work setup, routines, and collaboration',
    providers: ['ascension-native'],
    default_provider: 'ascension-native',
    cost_per_1k_tokens: 0,
    requires_tier: 'individual',
    executor: 'work'
  },
  {
    id: 'ascension_interview',
    name: 'Ascension Interview',
    category: 'work',
    description: 'Interview preparation and practice',
    providers: ['ascension-native'],
    default_provider: 'ascension-native',
    cost_per_1k_tokens: 0,
    requires_tier: 'individual',
    executor: 'work'
  },
  {
    id: 'ascension_resume',
    name: 'Ascension Resume',
    category: 'work',
    description: 'Resume and cover letter review',
    providers: ['ascension-native'],
    default_provider: 'ascension-native',
    cost_per_1k_tokens: 0,
    requires_tier: 'individual',
    executor: 'work'
  },
  {
    id: 'ascension_negotiation',
    name: 'Ascension Negotiation',
    category: 'work',
    description: 'Salary, contract, and negotiation strategy',
    providers: ['ascension-native'],
    default_provider: 'ascension-native',
    cost_per_1k_tokens: 0,
    requires_tier: 'individual',
    executor: 'work'
  },
  {
    id: 'ascension_networking',
    name: 'Ascension Networking',
    category: 'work',
    description: 'Professional networking and relationship building',
    providers: ['ascension-native'],
    default_provider: 'ascension-native',
    cost_per_1k_tokens: 0,
    requires_tier: 'individual',
    executor: 'work'
  },
  {
    id: 'ascension_leadership',
    name: 'Ascension Leadership',
    category: 'work',
    description: 'Leadership, management, and team guidance',
    providers: ['ascension-native'],
    default_provider: 'ascension-native',
    cost_per_1k_tokens: 0,
    requires_tier: 'individual',
    executor: 'work'
  },
  {
    id: 'ascension_team',
    name: 'Ascension Team',
    category: 'work',
    description: 'Team dynamics, conflict, and collaboration',
    providers: ['ascension-native'],
    default_provider: 'ascension-native',
    cost_per_1k_tokens: 0,
    requires_tier: 'individual',
    executor: 'work'
  },
  {
    id: 'ascension_feedback',
    name: 'Ascension Feedback',
    category: 'work',
    description: 'Giving and receiving feedback effectively',
    providers: ['ascension-native'],
    default_provider: 'ascension-native',
    cost_per_1k_tokens: 0,
    requires_tier: 'individual',
    executor: 'work'
  },
  {
    id: 'ascension_yoga',
    name: 'Ascension Yoga',
    category: 'wellness',
    description: 'Yoga poses, sequences, and practice guidance',
    providers: ['ascension-native'],
    default_provider: 'ascension-native',
    cost_per_1k_tokens: 0,
    requires_tier: 'individual',
    executor: 'wellness'
  },
  {
    id: 'ascension_running',
    name: 'Ascension Running',
    category: 'wellness',
    description: 'Running plans, form, and training progression',
    providers: ['ascension-native'],
    default_provider: 'ascension-native',
    cost_per_1k_tokens: 0,
    requires_tier: 'individual',
    executor: 'wellness'
  },
  {
    id: 'ascension_swimming',
    name: 'Ascension Swimming',
    category: 'wellness',
    description: 'Swim technique, workouts, and training',
    providers: ['ascension-native'],
    default_provider: 'ascension-native',
    cost_per_1k_tokens: 0,
    requires_tier: 'individual',
    executor: 'wellness'
  },
  {
    id: 'ascension_cycling',
    name: 'Ascension Cycling',
    category: 'wellness',
    description: 'Cycling routes, training, and equipment',
    providers: ['ascension-native'],
    default_provider: 'ascension-native',
    cost_per_1k_tokens: 0,
    requires_tier: 'individual',
    executor: 'wellness'
  },
  {
    id: 'ascension_hiking',
    name: 'Ascension Hiking',
    category: 'wellness',
    description: 'Hiking preparation, trails, and safety',
    providers: ['ascension-native'],
    default_provider: 'ascension-native',
    cost_per_1k_tokens: 0,
    requires_tier: 'individual',
    executor: 'wellness'
  },
  {
    id: 'ascension_climbing',
    name: 'Ascension Climbing',
    category: 'wellness',
    description: 'Climbing technique, training, and safety',
    providers: ['ascension-native'],
    default_provider: 'ascension-native',
    cost_per_1k_tokens: 0,
    requires_tier: 'individual',
    executor: 'wellness'
  },
  {
    id: 'ascension_martialarts',
    name: 'Ascension Martial Arts',
    category: 'wellness',
    description: 'Martial arts style guidance, drills, and conditioning',
    providers: ['ascension-native'],
    default_provider: 'ascension-native',
    cost_per_1k_tokens: 0,
    requires_tier: 'individual',
    executor: 'wellness'
  },
  {
    id: 'ascension_skincare',
    name: 'Ascension Skincare',
    category: 'wellness',
    description: 'Skincare routines, ingredients, and concerns',
    providers: ['ascension-native'],
    default_provider: 'ascension-native',
    cost_per_1k_tokens: 0,
    requires_tier: 'individual',
    executor: 'wellness'
  },
  {
    id: 'ascension_ergonomics',
    name: 'Ascension Ergonomics',
    category: 'wellness',
    description: 'Desk, posture, and workspace ergonomics',
    providers: ['ascension-native'],
    default_provider: 'ascension-native',
    cost_per_1k_tokens: 0,
    requires_tier: 'individual',
    executor: 'wellness'
  },
  {
    id: 'ascension_firstaid',
    name: 'Ascension First Aid',
    category: 'wellness',
    description: 'First aid guidance and when to seek care',
    providers: ['ascension-native'],
    default_provider: 'ascension-native',
    cost_per_1k_tokens: 0,
    requires_tier: 'individual',
    executor: 'wellness'
  },
  {
    id: 'ascension_dance',
    name: 'Ascension Dance',
    category: 'creation',
    description: 'Dance styles, choreography, and practice',
    providers: ['ascension-native'],
    default_provider: 'ascension-native',
    cost_per_1k_tokens: 0,
    requires_tier: 'individual',
    executor: 'creation'
  },
  {
    id: 'ascension_photography',
    name: 'Ascension Photography',
    category: 'creation',
    description: 'Photography technique, composition, and editing guidance',
    providers: ['ascension-native'],
    default_provider: 'ascension-native',
    cost_per_1k_tokens: 0,
    requires_tier: 'individual',
    executor: 'creation'
  },
  {
    id: 'ascension_filmmaking',
    name: 'Ascension Filmmaking',
    category: 'creation',
    description: 'Film, video, and content production guidance',
    providers: ['ascension-native'],
    default_provider: 'ascension-native',
    cost_per_1k_tokens: 0,
    requires_tier: 'individual',
    executor: 'creation'
  },
  {
    id: 'ascension_podcast',
    name: 'Ascension Podcast',
    category: 'creation',
    description: 'Podcast planning, production, and distribution guidance',
    providers: ['ascension-native'],
    default_provider: 'ascension-native',
    cost_per_1k_tokens: 0,
    requires_tier: 'individual',
    executor: 'creation'
  },
  {
    id: 'ascension_design',
    name: 'Ascension Design',
    category: 'creation',
    description: 'Graphic, UX, and visual design guidance',
    providers: ['ascension-native'],
    default_provider: 'ascension-native',
    cost_per_1k_tokens: 0,
    requires_tier: 'individual',
    executor: 'creation'
  },
  {
    id: 'ascension_interior_design',
    name: 'Ascension Interior Design',
    category: 'home',
    description: 'Interior layout, color, and decor planning',
    providers: ['ascension-native'],
    default_provider: 'ascension-native',
    cost_per_1k_tokens: 0,
    requires_tier: 'individual',
    executor: 'home'
  },
  {
    id: 'ascension_craft',
    name: 'Ascension Craft',
    category: 'creation',
    description: 'Crafts, DIY, and maker project guidance',
    providers: ['ascension-native'],
    default_provider: 'ascension-native',
    cost_per_1k_tokens: 0,
    requires_tier: 'individual',
    executor: 'creation'
  },
  {
    id: 'ascension_baking',
    name: 'Ascension Baking',
    category: 'home',
    description: 'Baking recipes, technique, and troubleshooting',
    providers: ['ascension-native'],
    default_provider: 'ascension-native',
    cost_per_1k_tokens: 0,
    requires_tier: 'individual',
    executor: 'home'
  },
  {
    id: 'ascension_mixology',
    name: 'Ascension Mixology',
    category: 'home',
    description: 'Cocktail, mocktail, and beverage guidance',
    providers: ['ascension-native'],
    default_provider: 'ascension-native',
    cost_per_1k_tokens: 0,
    requires_tier: 'individual',
    executor: 'home'
  },
  {
    id: 'ascension_etiquette',
    name: 'Ascension Etiquette',
    category: 'knowledge',
    description: 'Etiquette, manners, and social situation guidance',
    providers: ['ascension-native'],
    default_provider: 'ascension-native',
    cost_per_1k_tokens: 0,
    requires_tier: 'individual',
    executor: 'knowledge'
  },
  {
    id: 'ascension_wedding',
    name: 'Ascension Wedding',
    category: 'life_events',
    description: 'Wedding planning, timeline, and etiquette',
    providers: ['ascension-native'],
    default_provider: 'ascension-native',
    cost_per_1k_tokens: 0,
    requires_tier: 'individual',
    executor: 'life_events'
  },
  {
    id: 'ascension_birthday',
    name: 'Ascension Birthday',
    category: 'life_events',
    description: 'Birthday planning, themes, and gift ideas',
    providers: ['ascension-native'],
    default_provider: 'ascension-native',
    cost_per_1k_tokens: 0,
    requires_tier: 'individual',
    executor: 'life_events'
  },
  {
    id: 'ascension_party',
    name: 'Ascension Party',
    category: 'life_events',
    description: 'Party planning, guest lists, and logistics',
    providers: ['ascension-native'],
    default_provider: 'ascension-native',
    cost_per_1k_tokens: 0,
    requires_tier: 'individual',
    executor: 'life_events'
  },
  {
    id: 'ascension_holiday',
    name: 'Ascension Holiday',
    category: 'life_events',
    description: 'Holiday planning, traditions, and travel',
    providers: ['ascension-native'],
    default_provider: 'ascension-native',
    cost_per_1k_tokens: 0,
    requires_tier: 'individual',
    executor: 'life_events'
  },
  {
    id: 'ascension_gift',
    name: 'Ascension Gift',
    category: 'life_events',
    description: 'Gift ideas, wrapping, and giving guidance',
    providers: ['ascension-native'],
    default_provider: 'ascension-native',
    cost_per_1k_tokens: 0,
    requires_tier: 'individual',
    executor: 'life_events'
  },
  {
    id: 'ascension_funeral',
    name: 'Ascension Funeral',
    category: 'life_events',
    description: 'Funeral planning, grief, and memorial support',
    providers: ['ascension-native'],
    default_provider: 'ascension-native',
    cost_per_1k_tokens: 0,
    requires_tier: 'individual',
    executor: 'life_events'
  },
  {
    id: 'ascension_babyshower',
    name: 'Ascension Baby Shower',
    category: 'life_events',
    description: 'Baby shower planning and registry guidance',
    providers: ['ascension-native'],
    default_provider: 'ascension-native',
    cost_per_1k_tokens: 0,
    requires_tier: 'individual',
    executor: 'life_events'
  },
  {
    id: 'ascension_graduation',
    name: 'Ascension Graduation',
    category: 'life_events',
    description: 'Graduation planning, gifts, and next steps',
    providers: ['ascension-native'],
    default_provider: 'ascension-native',
    cost_per_1k_tokens: 0,
    requires_tier: 'individual',
    executor: 'life_events'
  },
  {
    id: 'ascension_retirement',
    name: 'Ascension Retirement',
    category: 'life_events',
    description: 'Retirement planning, lifestyle, and transitions',
    providers: ['ascension-native'],
    default_provider: 'ascension-native',
    cost_per_1k_tokens: 0,
    requires_tier: 'individual',
    executor: 'life_events'
  },
  {
    id: 'ascension_anniversary',
    name: 'Ascension Anniversary',
    category: 'life_events',
    description: 'Anniversary celebration and gift ideas',
    providers: ['ascension-native'],
    default_provider: 'ascension-native',
    cost_per_1k_tokens: 0,
    requires_tier: 'individual',
    executor: 'life_events'
  },
  {
    id: 'ascension_homework',
    name: 'Ascension Homework',
    category: 'education',
    description: 'Homework help, explanation, and study guidance',
    providers: ['ascension-native'],
    default_provider: 'ascension-native',
    cost_per_1k_tokens: 0,
    requires_tier: 'individual',
    executor: 'education'
  },
  {
    id: 'ascension_tutor',
    name: 'Ascension Tutor',
    category: 'education',
    description: 'One-on-one tutoring across subjects',
    providers: ['ascension-native'],
    default_provider: 'ascension-native',
    cost_per_1k_tokens: 0,
    requires_tier: 'individual',
    executor: 'education'
  },
  {
    id: 'ascension_school',
    name: 'Ascension School',
    category: 'education',
    description: 'School selection, applications, and planning',
    providers: ['ascension-native'],
    default_provider: 'ascension-native',
    cost_per_1k_tokens: 0,
    requires_tier: 'individual',
    executor: 'education'
  },
  {
    id: 'ascension_college',
    name: 'Ascension College',
    category: 'education',
    description: 'College search, applications, and planning',
    providers: ['ascension-native'],
    default_provider: 'ascension-native',
    cost_per_1k_tokens: 0,
    requires_tier: 'individual',
    executor: 'education'
  },
  {
    id: 'ascension_scholarship',
    name: 'Ascension Scholarship',
    category: 'education',
    description: 'Scholarship search and application support',
    providers: ['ascension-native'],
    default_provider: 'ascension-native',
    cost_per_1k_tokens: 0,
    requires_tier: 'individual',
    executor: 'education'
  },
  {
    id: 'ascension_exam',
    name: 'Ascension Exam',
    category: 'education',
    description: 'Exam preparation, strategy, and practice',
    providers: ['ascension-native'],
    default_provider: 'ascension-native',
    cost_per_1k_tokens: 0,
    requires_tier: 'individual',
    executor: 'education'
  },
  {
    id: 'ascension_studyskills',
    name: 'Ascension Study Skills',
    category: 'education',
    description: 'Study habits, note-taking, and retention',
    providers: ['ascension-native'],
    default_provider: 'ascension-native',
    cost_per_1k_tokens: 0,
    requires_tier: 'individual',
    executor: 'education'
  },
  {
    id: 'ascension_memorization',
    name: 'Ascension Memorization',
    category: 'education',
    description: 'Memory techniques and spaced repetition',
    providers: ['ascension-native'],
    default_provider: 'ascension-native',
    cost_per_1k_tokens: 0,
    requires_tier: 'individual',
    executor: 'education'
  },
  {
    id: 'ascension_presentation',
    name: 'Ascension Presentation',
    category: 'education',
    description: 'Presentations, slides, and public speaking',
    providers: ['ascension-native'],
    default_provider: 'ascension-native',
    cost_per_1k_tokens: 0,
    requires_tier: 'individual',
    executor: 'education'
  },
  {
    id: 'ascension_teaching',
    name: 'Ascension Teaching',
    category: 'education',
    description: 'Teaching methods, lesson planning, and assessment',
    providers: ['ascension-native'],
    default_provider: 'ascension-native',
    cost_per_1k_tokens: 0,
    requires_tier: 'individual',
    executor: 'education'
  },
  {
    id: 'ascension_devops',
    name: 'Ascension DevOps',
    category: 'engineering',
    description: 'DevOps practices, pipelines, and infrastructure',
    providers: ['ascension-native'],
    default_provider: 'ascension-native',
    cost_per_1k_tokens: 0,
    requires_tier: 'individual',
    executor: 'engineering'
  },
  {
    id: 'ascension_cloud',
    name: 'Ascension Cloud',
    category: 'engineering',
    description: 'Cloud architecture, services, and cost guidance',
    providers: ['ascension-native'],
    default_provider: 'ascension-native',
    cost_per_1k_tokens: 0,
    requires_tier: 'individual',
    executor: 'engineering'
  },
  {
    id: 'ascension_databases',
    name: 'Ascension Databases',
    category: 'engineering',
    description: 'Database design, queries, and optimization',
    providers: ['ascension-native'],
    default_provider: 'ascension-native',
    cost_per_1k_tokens: 0,
    requires_tier: 'individual',
    executor: 'engineering'
  },
  {
    id: 'ascension_security_tech',
    name: 'Ascension Security Tech',
    category: 'engineering',
    description: 'Application and infrastructure security guidance',
    providers: ['ascension-native'],
    default_provider: 'ascension-native',
    cost_per_1k_tokens: 0,
    requires_tier: 'individual',
    executor: 'engineering'
  },
  {
    id: 'ascension_testing',
    name: 'Ascension Testing',
    category: 'engineering',
    description: 'Test strategy, automation, and quality assurance',
    providers: ['ascension-native'],
    default_provider: 'ascension-native',
    cost_per_1k_tokens: 0,
    requires_tier: 'individual',
    executor: 'engineering'
  },
  {
    id: 'ascension_cicd',
    name: 'Ascension CI/CD',
    category: 'engineering',
    description: 'Continuous integration and delivery guidance',
    providers: ['ascension-native'],
    default_provider: 'ascension-native',
    cost_per_1k_tokens: 0,
    requires_tier: 'individual',
    executor: 'engineering'
  },
  {
    id: 'ascension_monitoring',
    name: 'Ascension Monitoring',
    category: 'engineering',
    description: 'Observability, logging, and alerting',
    providers: ['ascension-native'],
    default_provider: 'ascension-native',
    cost_per_1k_tokens: 0,
    requires_tier: 'individual',
    executor: 'engineering'
  },
  {
    id: 'ascension_api',
    name: 'Ascension API',
    category: 'engineering',
    description: 'API design, versioning, and documentation',
    providers: ['ascension-native'],
    default_provider: 'ascension-native',
    cost_per_1k_tokens: 0,
    requires_tier: 'individual',
    executor: 'engineering'
  },
  {
    id: 'ascension_microservices',
    name: 'Ascension Microservices',
    category: 'engineering',
    description: 'Microservices architecture and tradeoffs',
    providers: ['ascension-native'],
    default_provider: 'ascension-native',
    cost_per_1k_tokens: 0,
    requires_tier: 'individual',
    executor: 'engineering'
  },
  {
    id: 'ascension_blockchain',
    name: 'Ascension Blockchain',
    category: 'engineering',
    description: 'Blockchain concepts, smart contracts, and crypto basics',
    providers: ['ascension-native'],
    default_provider: 'ascension-native',
    cost_per_1k_tokens: 0,
    requires_tier: 'individual',
    executor: 'engineering'
  },
  {
    id: 'ascension_walking',
    name: 'Ascension Walking',
    category: 'wellness',
    description: 'Walking plans, routes, and fitness integration',
    providers: ['ascension-native'],
    default_provider: 'ascension-native',
    cost_per_1k_tokens: 0,
    requires_tier: 'individual',
    executor: 'wellness'
  },
  {
    id: 'ascension_stretching',
    name: 'Ascension Stretching',
    category: 'wellness',
    description: 'Stretching routines, mobility, and flexibility',
    providers: ['ascension-native'],
    default_provider: 'ascension-native',
    cost_per_1k_tokens: 0,
    requires_tier: 'individual',
    executor: 'wellness'
  },
  {
    id: 'ascension_recovery',
    name: 'Ascension Recovery',
    category: 'wellness',
    description: 'Rest, recovery, and regeneration planning',
    providers: ['ascension-native'],
    default_provider: 'ascension-native',
    cost_per_1k_tokens: 0,
    requires_tier: 'individual',
    executor: 'wellness'
  },
  {
    id: 'ascension_supplements',
    name: 'Ascension Supplements',
    category: 'wellness',
    description: 'Supplement information and when to consult a clinician',
    providers: ['ascension-native'],
    default_provider: 'ascension-native',
    cost_per_1k_tokens: 0,
    requires_tier: 'individual',
    executor: 'wellness'
  },
  {
    id: 'ascension_allergies',
    name: 'Ascension Allergies',
    category: 'wellness',
    description: 'Allergy awareness, triggers, and management',
    providers: ['ascension-native'],
    default_provider: 'ascension-native',
    cost_per_1k_tokens: 0,
    requires_tier: 'individual',
    executor: 'wellness'
  },
  {
    id: 'ascension_chronic',
    name: 'Ascension Chronic',
    category: 'wellness',
    description: 'Chronic condition support and self-management guidance',
    providers: ['ascension-native'],
    default_provider: 'ascension-native',
    cost_per_1k_tokens: 0,
    requires_tier: 'individual',
    executor: 'wellness'
  },
  {
    id: 'ascension_disability',
    name: 'Ascension Disability',
    category: 'wellness',
    description: 'Disability support, accommodations, and resources',
    providers: ['ascension-native'],
    default_provider: 'ascension-native',
    cost_per_1k_tokens: 0,
    requires_tier: 'individual',
    executor: 'wellness'
  },
  {
    id: 'ascension_pregnancy',
    name: 'Ascension Pregnancy',
    category: 'wellness',
    description: 'Pregnancy planning, questions, and resource guidance',
    providers: ['ascension-native'],
    default_provider: 'ascension-native',
    cost_per_1k_tokens: 0,
    requires_tier: 'individual',
    executor: 'wellness'
  },
  {
    id: 'ascension_childbirth',
    name: 'Ascension Childbirth',
    category: 'wellness',
    description: 'Childbirth preparation and birth plan support',
    providers: ['ascension-native'],
    default_provider: 'ascension-native',
    cost_per_1k_tokens: 0,
    requires_tier: 'individual',
    executor: 'wellness'
  },
  {
    id: 'ascension_postpartum',
    name: 'Ascension Postpartum',
    category: 'wellness',
    description: 'Postpartum support, recovery, and newborn adjustment',
    providers: ['ascension-native'],
    default_provider: 'ascension-native',
    cost_per_1k_tokens: 0,
    requires_tier: 'individual',
    executor: 'wellness'
  },
  {
    id: 'ascension_packing',
    name: 'Ascension Packing',
    category: 'home',
    description: 'Packing lists and travel preparation',
    providers: ['ascension-native'],
    default_provider: 'ascension-native',
    cost_per_1k_tokens: 0,
    requires_tier: 'individual',
    executor: 'home'
  },
  {
    id: 'ascension_commute',
    name: 'Ascension Commute',
    category: 'home',
    description: 'Commute planning, routes, and optimization',
    providers: ['ascension-native'],
    default_provider: 'ascension-native',
    cost_per_1k_tokens: 0,
    requires_tier: 'individual',
    executor: 'home'
  },
  {
    id: 'ascension_laundry',
    name: 'Ascension Laundry',
    category: 'home',
    description: 'Laundry routines, stains, and care',
    providers: ['ascension-native'],
    default_provider: 'ascension-native',
    cost_per_1k_tokens: 0,
    requires_tier: 'individual',
    executor: 'home'
  },
  {
    id: 'ascension_organizing',
    name: 'Ascension Organizing',
    category: 'home',
    description: 'Organization systems and decluttering',
    providers: ['ascension-native'],
    default_provider: 'ascension-native',
    cost_per_1k_tokens: 0,
    requires_tier: 'individual',
    executor: 'home'
  },
  {
    id: 'ascension_storage',
    name: 'Ascension Storage',
    category: 'home',
    description: 'Storage solutions and space planning',
    providers: ['ascension-native'],
    default_provider: 'ascension-native',
    cost_per_1k_tokens: 0,
    requires_tier: 'individual',
    executor: 'home'
  },
  {
    id: 'ascension_decor',
    name: 'Ascension Decor',
    category: 'home',
    description: 'Decor choices, themes, and styling',
    providers: ['ascension-native'],
    default_provider: 'ascension-native',
    cost_per_1k_tokens: 0,
    requires_tier: 'individual',
    executor: 'home'
  },
  {
    id: 'ascension_lighting',
    name: 'Ascension Lighting',
    category: 'home',
    description: 'Lighting design, bulbs, and ambiance',
    providers: ['ascension-native'],
    default_provider: 'ascension-native',
    cost_per_1k_tokens: 0,
    requires_tier: 'individual',
    executor: 'home'
  },
  {
    id: 'ascension_sound',
    name: 'Ascension Sound',
    category: 'home',
    description: 'Sound, acoustics, and noise management',
    providers: ['ascension-native'],
    default_provider: 'ascension-native',
    cost_per_1k_tokens: 0,
    requires_tier: 'individual',
    executor: 'home'
  },
  {
    id: 'ascension_smell',
    name: 'Ascension Smell',
    category: 'home',
    description: 'Scent, air quality, and fragrance guidance',
    providers: ['ascension-native'],
    default_provider: 'ascension-native',
    cost_per_1k_tokens: 0,
    requires_tier: 'individual',
    executor: 'home'
  },
  {
    id: 'ascension_balcony',
    name: 'Ascension Balcony',
    category: 'home',
    description: 'Balcony, patio, and small outdoor space use',
    providers: ['ascension-native'],
    default_provider: 'ascension-native',
    cost_per_1k_tokens: 0,
    requires_tier: 'individual',
    executor: 'home'
  },
  {
    id: 'ascension_will',
    name: 'Ascension Will',
    category: 'legal',
    description: 'Will planning and estate introduction',
    providers: ['ascension-native'],
    default_provider: 'ascension-native',
    cost_per_1k_tokens: 0,
    requires_tier: 'individual',
    executor: 'legal'
  },
  {
    id: 'ascension_trust',
    name: 'Ascension Trust',
    category: 'legal',
    description: 'Trust basics and estate planning guidance',
    providers: ['ascension-native'],
    default_provider: 'ascension-native',
    cost_per_1k_tokens: 0,
    requires_tier: 'individual',
    executor: 'legal'
  },
  {
    id: 'ascension_prenup',
    name: 'Ascension Prenup',
    category: 'legal',
    description: 'Prenuptial agreement information and attorney referral',
    providers: ['ascension-native'],
    default_provider: 'ascension-native',
    cost_per_1k_tokens: 0,
    requires_tier: 'individual',
    executor: 'legal'
  },
  {
    id: 'ascension_divorce',
    name: 'Ascension Divorce',
    category: 'legal',
    description: 'Divorce information and resource guidance',
    providers: ['ascension-native'],
    default_provider: 'ascension-native',
    cost_per_1k_tokens: 0,
    requires_tier: 'individual',
    executor: 'legal'
  },
  {
    id: 'ascension_custody',
    name: 'Ascension Custody',
    category: 'legal',
    description: 'Child custody information and co-parenting resources',
    providers: ['ascension-native'],
    default_provider: 'ascension-native',
    cost_per_1k_tokens: 0,
    requires_tier: 'individual',
    executor: 'legal'
  },
  {
    id: 'ascension_adoption',
    name: 'Ascension Adoption',
    category: 'legal',
    description: 'Adoption information, steps, and resources',
    providers: ['ascension-native'],
    default_provider: 'ascension-native',
    cost_per_1k_tokens: 0,
    requires_tier: 'individual',
    executor: 'legal'
  },
  {
    id: 'ascension_immigration',
    name: 'Ascension Immigration',
    category: 'legal',
    description: 'Immigration path overview and document organization',
    providers: ['ascension-native'],
    default_provider: 'ascension-native',
    cost_per_1k_tokens: 0,
    requires_tier: 'individual',
    executor: 'legal'
  },
  {
    id: 'ascension_contracts',
    name: 'Ascension Contracts',
    category: 'legal',
    description: 'Contract review preparation and plain-language explanations',
    providers: ['ascension-native'],
    default_provider: 'ascension-native',
    cost_per_1k_tokens: 0,
    requires_tier: 'individual',
    executor: 'legal'
  },
  {
    id: 'ascension_tenant',
    name: 'Ascension Tenant',
    category: 'legal',
    description: 'Tenant rights, leases, and rental issues',
    providers: ['ascension-native'],
    default_provider: 'ascension-native',
    cost_per_1k_tokens: 0,
    requires_tier: 'individual',
    executor: 'legal'
  },
  {
    id: 'ascension_landlord',
    name: 'Ascension Landlord',
    category: 'legal',
    description: 'Landlord responsibilities, leases, and tenant issues',
    providers: ['ascension-native'],
    default_provider: 'ascension-native',
    cost_per_1k_tokens: 0,
    requires_tier: 'individual',
    executor: 'legal'
  },
  
  // Add 180+ more capabilities here...
];

export function getCapabilityById(id: string) {
  return CAPABILITIES.find(c => c.id === id);
}

export function getCapabilitiesByCategory(category: string) {
  return CAPABILITIES.filter(c => c.category === category);
}

export function getCapabilitiesByTier(tier: string) {
  return CAPABILITIES.filter(c => c.requires_tier === tier || c.requires_tier === 'individual');
}

export function getAllCapabilities() {
  return CAPABILITIES;
}
